db:
  name: wp-database
  labels:
    app: db
    env: dev
    stack: wordpress
  image:
    repository: wordpress:latest
    tag: v2
    pullPolicy: Always
  replicas: 1
  configmap:
    ## KEY: "value"
    MYSQL_DATABASE: 0927408
    MYSQL_USER: sagar
    APP_ENV: dev
  containerPorts:
      mysql: 3306
