apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  labels:
    app: db
    env: dev
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: MDkyNzQwOA==          ## base64 encoded value of original password - command: echo -n 123456789 | base64
  MYSQL_PASSWORD: MTIzNDU2Nzg5Cg==