# Service file

apiVersion: v1
kind: Service
metadata:
  name: mariadb-service
spec:
  type: ClusterIP
  selector:
    app: db
    env: dev
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306