apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secret
  labels:
    app: wp-app
    env: dev
type: Opaque
data:           ## base64 encoded value of original password - command: echo -n 123456789 | base64
  WORDPRESS_DB_PASSWORD: MTIzNDU2Nzg5Cg==