---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
spec:
  type: ClusterIP
  selector:
    app: wp-app
    env: dev
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

