apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-configmap
  labels:
    app: wp-app
    env: dev
data:
  WORDPRESS_DB_HOST: "mariadb-service.db.svc.cluster.local"
  WORDPRESS_DB_USER: "sagar"
  WORDPRESS_DB_NAME: "wordpress"
  