# Deployment file
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-proxy
spec:
  selector:
    matchLabels:
      id: C0927408
  replicas: 3
  template:
    metadata:
      labels:
        id: C0927408
        app: nginx-proxy
        env: dev
    spec:
      containers:
      - name: nginx-proxy
        image: gireesagar/nginx-proxy:v3
        ports:
        - containerPort: 80


